### ISSUE TITLE
Define audience header parameter

### ISSUE THREAD

**Issue by dwaite** [json-web-proofs/json-web-proofs#102]
Define the use of an `"aud"` presentation header parameter to be suggested alongside `"nonce"`

**Comment by selfissued** [comment]
I believe that `aud` should be a claim rather than a header parameter.  Same with `nonce`.

But I agree that we should discuss this.

**Comment by dwaite** [comment]
Clarifying - `aud` makes sense as a presentation header parameter, for use of protocols which use this to target a particular verifier.
