### ISSUE TITLE
Define how JOSE registered header parameters apply to a JWP

### ISSUE THREAD

**Issue by quartzjer** [json-web-proofs/json-web-proofs#19]
For example, all of the ones defined in [JWS](https://datatracker.ietf.org/doc/html/rfc7515) apply the same, except `cty` should be documented as not recommended.

**Comment by selfissued** [comment]
I agree that we need to do this analysis.

**Comment by dwaite** [comment]
Has this been completed by the recent IANA section work?

**Comment by selfissued** [comment]
Fixed by PR #106
