### ISSUE TITLE
Move JPA request parts to subsections

### ISSUE THREAD

**Issue by quartzjer** [json-web-proofs/json-web-proofs#21]
Also add recommendation that algorithms support a single octet string serialization for higher level protocols.

**Comment by OR13** [comment]
yes, please times 1,000.... never again with EC point compression patent work arounds...

**Comment by dwaite** [comment]
We need clarification on what change is pending for this issue, or if it has been resolved

**Comment by selfissued** [comment]
I believe this was addressed by https://github.com/json-web-proofs/json-web-proofs/pull/106, which defined the `alg` header parameter.
