### ISSUE TITLE
Define what the JWK Thumbprint is of a JWK with layout information

### ISSUE THREAD

**Issue by selfissued** [json-web-proofs/json-web-proofs#23]
Given we're proposing to add additional information to the JWKs we use, I believe that we need to define how this additional information is used or not used by JWK Thumbprints (https://www.rfc-editor.org/rfc/rfc7638.html).  I would propose that the additional members be ignored, just as other information such as "use", etc. are ignored, since they are not "required members".

**Comment by quartzjer** [comment]
👍, agree they are ignored, the thumbprint will be the same for the same key material.

**Comment by OR13** [comment]
I remain opposed to including `lyt` in JWKs... it does not belong there... it belongs in the protected header... its a property of the proof produced, not the key used to produce it.

**Comment by quartzjer** [comment]
Since the `lyt` and the direct association of it with the JWK have been removed from the latest drafts, I'm going to close this issue.
