### ISSUE TITLE
Indirect references in layouts seem inconsistent with being URL-safe

### ISSUE THREAD

**Issue by selfissued** [json-web-proofs/json-web-proofs#26]
JTPs are URL-safe but allowing binary portions of them via indirect references seems inconsistent.  Or was the intent that the payload be the base64url-encoded representation of the binary indirectly referenced object, such as a an object with media type `image/jpeg`?  If so, this language needs to be clarified.

**Comment by quartzjer** [comment]
> Or was the intent that the payload be the base64url-encoded representation of the binary indirectly referenced object

That was indeed the intent of the original language.

I am starting to think that a JPT should be only strictly JSON values the same as a JWT.  JWP can support binary payloads for those use-cases, but the cost of trying to support their representation in a JPT is seeming like it only adds more complexity and diverges from trying to minimize the changes from a JWT.

**Comment by OR13** [comment]
Yes, I would stick to figuring this out in JSON first, then tackle binary and adjust the JSON side if any awkwardness is discovered... bad idea to do both at the same time imo.

**Comment by quartzjer** [comment]
I'm going to close this as indirect references have been removed and I agree w/ @OR13 to stick to JSON and tackle binary later (if/when necessary).
