### ISSUE TITLE
Payloads can be predicates - not just claims

### ISSUE THREAD

**Issue by selfissued** [json-web-proofs/json-web-proofs#27]
There are a number of places in the current drafts where we say that predicates represent claims but we fail to say that they can also represent predicates.  We should develop consistent language for describing both and uniformly use it.

**Comment by quartzjer** [comment]
> There are a number of places in the current drafts where we say that predicates represent claims

I think you mean where we say that payloads represent claims?

Regardless, there definitely needs to be consistent language around how predicate proofs are expected to be done.

**Comment by selfissued** [comment]
Yes, I we need to say that payloads can represent claims or predicate proofs.

**Comment by quartzjer** [comment]
> that payloads can represent claims or predicate proofs.

Technically, payloads can represent claims, but they do _not_ represent predicate proofs (unless the claim itself is a form of a predicate proof from the issuer, such as a hashchain, which are just integrity protected as any other claim would be).

Any predicate proofs generated during a `prove` operation are combined into the singular resulting `proof` value.

We touched on this during the meeting today: predicate proof representations are specific to the underlying JPA and are never understandable or useful directly to the application.  Only the JPA implementation can properly encode/decode and verify them along with how it binds them to a particular slot.

**Comment by quartzjer** [comment]
I think the language can be made more consistent in all three drafts around exactly what a payload represents separate from proofs.  Marking this as a TODO.
