### ISSUE TITLE
Use different claim name than 'alg' for JPAs?

### ISSUE THREAD

**Issue by quartzjer** [json-web-proofs/json-web-proofs#29]
Since none of the JWA values for `alg` will work for a JWP, is using the same `alg` claim name to reference them potentially confusing?  For example, should we use `jwa` instead to identify the algorithm name in the protected header?

There is definitely no case where both `alg` and `jwa` could both be used, but it is possible that a JPA could be defined to _also_ work for a traditional JWS, such as "BBS+" for example.

It seems to make sense to use the same value and registry, with just the caveat that some algorithm definitions will only work for proofs and most will not, similar to encryption or signing?

**Comment by selfissued** [comment]
I think it's more JOSE-like to use `alg` and to specify that some `alg` values only work for proofs (just like some `alg` values work for signatures and some work for encryption).

**Comment by quartzjer** [comment]
Agree, sticking with `alg`, closing this issue.
