### ISSUE TITLE
Are JSON object claims supported?

### ISSUE THREAD

**Issue by OR13** [json-web-proofs/json-web-proofs#33]
Trivial claims, like these can easily be mapped to a payload array.

```
 "claims": [
    "iat",
    "exp",
    "family_name",
    "given_name",
    "email"
  ]
```

Our use cases involve complex object usually of specific types... 

How are objects supported by this spec?

**Comment by quartzjer** [comment]
Any of those claim names can be an object value (or any JSON value).

The processing of a complete JWP/JPT cannot itself be represented as a singular JSON object, each payload is a standalone  that has only a cryptographic association with the other payloads.

**Comment by quartzjer** [comment]
I'm going to mark this as a TODO for the next revision of JPT, to add an example claim that is a JSON object.

**Comment by selfissued** [comment]
Yes, we certainly want to be able to have claims like "address" that are structured.  However, I don't think we want to go down the road that SD-JWT did to enable disclosure of parts of structured claims.  Like others, they should be all-or-nothing.

**Comment by dwaite** [comment]
yes, I'll just add a single `address` claim as a JSON object to the examples.
