### ISSUE TITLE
It would seem more logical to have the JWP Protected Header signature be the first one, not the last one

### ISSUE THREAD

**Issue by selfissued** [json-web-proofs/json-web-proofs#38]
The JPA spec currently says:
> To prepare the JWP for signing or verification a Parts List is created.  Each payload octet string is placed into the Parts List preserving their order from the JWP.  The JWP Protected Header octet string is then appended to this list as the last element

If I were designing this, I would have put the header signature first so that it always falls in the same place.  Currently its location is dependent upon the number of payload elements.  Can we agree to put it first?

**Comment by quartzjer** [comment]
That was my first instinct as well.

The reason I flipped it was thinking about it from an implementors perspective: knowing that the proof value is an array of fixed-size signatures, so the obvious first thing to do is something like `sigs_array = proof.split(size_of_signature)`.  My thought was it could be more consistent to have that array's indexes be identical to the array of payloads in the JWP, you can't get an off-by-one error with that approach.

The protected header signature would then be `sigs_array[-2]` and the signer's public signature would be `sigs_array[-1]`.

It seemed potentially less error-prone vs. asking the implementor to pop/shift/sub-slice/etc.

I'm perfectly comfortable flipping the order around if that's more logical.

**Comment by selfissued** [comment]
I'd really prefer to put them in the order
(1) signature of the protected header,
(2) signatures over the payloads,
(3) public signature.

I want that because then the signatures occur in the same order as the things being signed.  Thanks.

**Comment by dwaite** [comment]
Note that you don't need a signature of the protected header wrapped into the overarching signature - you can create the payload for the overall signature by concatenate the protected header of the JWP with the signatures of the individual payloads.

This payload is synthetic from the protected header and proof, so approach just saves one signature in space and computational budget.

**Comment by selfissued** [comment]
I don't understand what data structure you're proposing from the above comment, DW.  Can you be explicit about what signatures over what plaintexts you want to appear in what order?  And for bonus points, why?  Thanks.

**Comment by dwaite** [comment]
Note: Variables refer to non-base64-encoded values, e.g. UTF8 JSON text for headers and binary data for payloads.

Given:
- protected header `jwpph` with:
  - `alg` algorithm for single use referencing underlying algorithm `ualg`, e.g. `alg` of `SU-ES256` and `ualg` of `ES256`
  - understood applicable public key `pk` compatible with `ualg`
  - a `proof_jwk` header value for an ephemeral JWK `epk` compatible with `ualg`
- `payloads[0...n]`
 
To issue:
1. Create a predictable, synthesized protected header `sph` based on the underlying algorithm `ualg`. For example, the algorithm `SU-ES256` creates a synthesized protected header `sph` of `{"alg":"ES256"}`
2. For each `payload[n]`:

   2.1.   create a JWS with the synthesized protected header `sph` and the payload value `payload[n]`, signed by the key `epk`.
   2.2.  Capture the payload signature `psig[n]`

3. Compute overarching signature:

   3.1.  Create a JWS with the synthesized protected header `sph` and a payload containing a concatenation of the JWP protected header `jwpph` and each `psig[0...n]`, signed by the key `pk`.
   3.2.  Capture the overarching signature `osig`
 
4. The proof is the concatenation of `psig[0...n]` and `osig`.

To verify:
1. Crete synthetic protected header as above
2. Split proof into `psig[0...n]` and `osig`.
3. Verify overarching signature using `sph`, the concatenation of `jwpph` and `psig[0...n]`, and `pk`.
4. For each disclosed `payload[n]`:

   4.1 Verify payload signature using `sph`, `psig[n]`, and `epk`.

To derive:
1. Delete payload slots which you do not wish to disclose

**Comment by dwaite** [comment]
I'm also having a separate discussion on whether `epk` is needed, or if it is meant to avoid the potential misuse of component signatures.

**Comment by quartzjer** [comment]
I'm going to close this as the latest draft has the suggested ordering.
