### ISSUE TITLE
Types of / Definition of "Binding"

### ISSUE THREAD

**Issue by quartzjer** [json-web-proofs/json-web-proofs#41]
When supporting unlinkability, a JPA can also support a form of "binding" that ensures any honest Prover is the only entity that can generate a valid proof when given a challenge from a Verifier.

This algorithmic-level binding primitive is different and separate from any higher level types of binding such as using a DID in a payload, a protocol-based Proof of Posession, keychain signatures, or ephemeral keys.  All of those types of higher level bindings are not able to provide unlinkability for a Prover when presenting the same JWP to multiple Verifiers.

TODO: 
- [ ] Define Unlinkability (JWP)
- [ ] Define Unlinkable Binding (JPA)
- [ ] Define Linkable Binding (JPT)

**Comment by selfissued** [comment]
Per discussion with @dwaite on the JWP editors' call, we think that these should be defined in JWP.

**Comment by dwaite** [comment]
Merge #78 .
