### ISSUE TITLE
Using registered JWT claim names

### ISSUE THREAD

**Issue by Sakurann** [json-web-proofs/json-web-proofs#43]
Can registered JWT claim names be used? if so, how? 
For example, if I want to include issuance date and expiration date in JWP, should I use a header to do so?

**Comment by Sakurann** [comment]
Issue #36

**Comment by selfissued** [comment]
I believe we need to add that using registered JWT claims is the best practice to the JSON Proof Token specification.

**Comment by quartzjer** [comment]
I think we'll likely need a separate registry where we re-register all the existing JWT claims and explain any capabilities added by JWP (such as using predicate proofs).

The one exception from this that I can think of is the `iss` claim.  That one should be in the protected header and not a payload.

**Comment by dwaite** [comment]
The current JPT spec references that JWT claim names should come from the JWT IANA registry, and does not define any additional IANA registry for extending those claim values (such as providing for indicating capabilities like predicate proofs).

Current JWP guidance is that things like predicate proofs would not be claims, but rather be part of the proof value itself.

The `iss` issuer protected header value is now listed in an initial registry section under JWP IANA considerations.

I believe this can be closed.
