### ISSUE TITLE
Content type syntax for claims in payloads not fully general

### ISSUE THREAD

**Issue by selfissued** [json-web-proofs/json-web-proofs#5]
The example content type syntax for claims in payloads does not allow different content type values to apply to different claims in the same payload.  The current example syntax in the spec is:
`   "payloads":[
      {"claims":["family_name", "given_name"]},
      {"claims":["email"]},
      {"claims":["birthdate"]},
      {"claims":["age"], "cty":"hashchain-commitment"},
      {"claims":["profile_pic"], "cty":"image/png"}
   ]
`
I don't see a way to, for instance have have a `profile_pic_png` claim with content type `image/png` and a `profile_pic_jpg` claim with content type `image/jpeg` in the same payload.

**Comment by dwaite** [comment]
Would you be looking for something like:

``` json
[
  { "claims": ["profile_pic"], "cty": "image/png" },
  { "claims": ["profile_pic"], "cty": "image/jpeg" }
]
```

or

``` json
[
  { "claims": ["profile_pic_png"], "cty": "image/png" },
  { "claims": ["profile_pic_jpg"], "cty": "image/jpeg" }
]
```
