### ISSUE TITLE
Define and register media types for JWPs

### ISSUE THREAD

**Issue by gabrielbauman** [json-web-proofs/json-web-proofs#55]
[Media type(s)](https://datatracker.ietf.org/doc/html/rfc6838) for JWPs will need to be defined and registered.

For comparison, JWTs use `application/jwt+json`.

We could similarly use `application/jwp+json` and leave it to applications to determine which form is being parsed. We could also consider registering multiple media types, one for each form. I'm not sure what the best practice is in this case.

**Comment by selfissued** [comment]
Agreed, this is needed.

**Comment by dwaite** [comment]
Types are now registered within the JSON Web Proof IANA considerations
