### ISSUE TITLE
Allow algorithms to use ~ separator in proof values

### ISSUE THREAD

**Issue by quartzjer** [json-web-proofs/json-web-proofs#59]
Having worked on the SU and MAC algo drafts which both make use of proof values that are actually arrays, I would like to update the JPT core definition to treat all proof values as an array natively.

The array would be identical to how payloads are encoded, in compact it would use `~` separator, and in JSON it would simply be an array of base64url-encoded strings.

The JWP implementation would be required to always decode it into an array of individual variable-length octet strings and then pass that array into the algorithm, even if there is only one item.

This provides notable cryptographic simplification benefit to algorithm definitions, such that they don't have to internally define their own separators, padding, etc.

**Comment by dwaite** [comment]
I would be in favor of this. We do have signatures formed from combining binary data in JWA (such as ECDSA), but these have a fixed binary format. The addition of multiple payloads and of additional proof elements like predicate proofs would appear to create a need for dynamically sized binary data however, which means we are both putting on a burden for algorithms to create a scheme and a risk of additional out-of-bounds conditions in implementations.

This would mean we should probably make the JPA proof representation consistently into an array of binary values.

**Comment by selfissued** [comment]
Doing this makes sense to me.

**Comment by dwaite** [comment]
Will do a prototype to evaluate for draft 3

**Comment by dwaite** [comment]
Planning to add text to this, but the changes to algorithms to use it will likely be draft-4 milestone
