### ISSUE TITLE
Need IANA considerations

### ISSUE THREAD

**Issue by dwaite** [json-web-proofs/json-web-proofs#76]
From @OR13, https://mailarchive.ietf.org/arch/msg/jose/GkL3I9hEoKjaIDCgno_rYqQsSP0/ :

> It would be nice to see an initial table for the requested registry similar to how HPKE established registries:
>
>   * https://www.rfc-editor.org/rfc/rfc9180.html#name-algorithm-identifiers
>   * https://www.rfc-editor.org/rfc/rfc9180.html#name-kem-identifiers
>
> Similarly for any new reserved claims ( such as `pjwk` ), it would be nice to see them all in one place.

**Comment by selfissued** [comment]
I'll take a stab at creating a table for the header parameters we need.

We also need an algorithms registry.
